# Generated by Django 4.0.2 on 2022-02-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0005_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
