# Generated by Django 4.0.2 on 2022-02-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(max_length=254, null=True, upload_to='profile_pics/'),
        ),
    ]
