# Generated by Django 4.0.2 on 2022-02-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0002_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
