# Generated by Django 4.0.2 on 2022-02-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(max_length=254, null=True, upload_to='profile_pics/'),
        ),
    ]
