# Generated by Django 4.0 on 2022-02-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.FileField(upload_to=''),
        ),
    ]
