# Generated by Django 4.0 on 2022-02-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0003_alter_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.FileField(max_length=254, upload_to='uploads/'),
        ),
    ]
