# Generated by Django 4.0 on 2022-02-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0004_alter_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
